"""Tests for the `architect report` command.

Covers Rich table rendering, JSON output, SUMMARY.md parsing,
project path resolution, and edge cases (missing, empty, corrupted files).
"""

from __future__ import annotations

import json
from pathlib import Path

from click.testing import CliRunner

from the_architect.cli import (
    _format_report_json,
    _parse_summary_md,
    main,
)

# ---------------------------------------------------------------------------
# Fixtures — SUMMARY.md content generated by success.py's write_success_md()
# ---------------------------------------------------------------------------

# Minimal SUMMARY.md with one done task (matches success.py format)
MINIMAL_SUMMARY = """\
# The Architect — Run Summary

**Date:** 2026-05-18 14:30
**Duration:** 12:34
**Result:** ✓ All tasks completed

## Goal

Add a new feature to the application

## Tasks

| Task | Title | Status | Attempts | Model | Duration | Tokens |
|------|-------|--------|----------|-------|----------|--------|
| T01 | setup_project | ✓ Done | 1 | claude-sonnet-4 | 3:45 | 12.3K |

## Totals

- **Tasks:** 1/1 done
- **Duration:** 12:34
- **Total tokens:** 12.3K
- **Token breakdown:** input 10K · output 2.3K
- **Models:** anthropic/claude-sonnet-4

## Insights

- **Avg duration per task:** 3:45
- **Slowest task:** T01 setup_project (3:45)
- **Avg tokens per task:** 12.3K
- **Throughput:** 984 tokens/min
- **Most tokens:** T01 setup_project (12.3K)
"""

# SUMMARY.md with multiple tasks
MULTI_TASK_SUMMARY = """\
# The Architect — Run Summary

**Date:** 2026-05-18 15:00
**Duration:** 45:22
**Result:** ✓ All tasks completed

## Goal

Implement user authentication system

## Tasks

| Task | Title | Status | Attempts | Model | Duration | Tokens |
|------|-------|--------|----------|-------|----------|--------|
| T01 | auth_models | ✓ Done | 1 | claude-sonnet-4 | 8:12 | 25.1K |
| T02 | auth_endpoints | ✓ Done | 2 | claude-sonnet-4 | 15:30 | 42.7K |
| T03 | auth_tests | ✓ Done | 1 | claude-sonnet-4 | 12:00 | 18.5K |

## Totals

- **Tasks:** 3/3 done
- **Duration:** 45:22
- **Total tokens:** 86.3K
- **Token breakdown:** input 65K · output 21.3K
- **Models:** anthropic/claude-sonnet-4
- **Retries:** 1 across 3 tasks

## Insights

- **Avg duration per task:** 11:54
- **Slowest task:** T02 auth_endpoints (15:30)
- **Avg tokens per task:** 28.8K
- **Throughput:** 1900 tokens/min
- **Most tokens:** T02 auth_endpoints (42.7K)
- **Most retries:** T02 auth_endpoints (2 attempts)
"""

# SUMMARY.md with a failed task
FAILED_TASK_SUMMARY = """\
# The Architect — Run Summary

**Date:** 2026-05-18 16:00
**Duration:** 20:15
**Result:** ✗ 1 task(s) failed

## Goal

Add database migration

## Tasks

| Task | Title | Status | Attempts | Model | Duration | Tokens |
|------|-------|--------|----------|-------|----------|--------|
| T01 | migration_script | ✓ Done | 1 | gpt-4o | 5:30 | 8.2K |
| T02 | migration_tests | ✗ Failed | 3 | gpt-4o | 12:45 | 22.1K |

## Totals

- **Tasks:** 1/2 done
- **Duration:** 20:15
- **Total tokens:** 30.3K
- **Token breakdown:** input 22K · output 8.3K
- **Models:** openai/gpt-4o
- **Retries:** 2 across 2 tasks

## Insights

- **Avg duration per task:** 5:30
- **Slowest task:** T01 migration_script (5:30)
- **Avg tokens per task:** 8.2K
- **Throughput:** 150 tokens/min
- **Most tokens:** T01 migration_script (8.2K)
"""

# SUMMARY.md with retrospective rounds
RETROSPECTIVE_SUMMARY = """\
# The Architect — Run Summary

**Date:** 2026-05-18 17:00
**Duration:** 60:00
**Result:** ✓ All tasks completed

## Goal

Refactor payment processing module

## Tasks

| Task | Title | Status | Attempts | Model | Duration | Tokens |
|------|-------|--------|----------|-------|----------|--------|
| T01 | payment_refactor | ✓ Done | 1 | claude-sonnet-4 | 20:00 | 35.0K |

## Retrospective

| Round | Issues Found | Fix-up Tasks | Validation | Duration |
|-------|-------------|-------------|------------|----------|
| 1 | 2 | R01, R02 | ✓ Passed | 15:00 |

## Totals

- **Tasks:** 1/1 done
- **Duration:** 60:00
- **Total tokens:** 35.0K
- **Token breakdown:** input 25K · output 10K
- **Models:** anthropic/claude-sonnet-4

## Insights

- **Avg duration per task:** 20:00
- **Slowest task:** T01 payment_refactor (20:00)
- **Avg tokens per task:** 35.0K
- **Throughput:** 583 tokens/min
- **Most tokens:** T01 payment_refactor (35.0K)
"""

# ---------------------------------------------------------------------------
# Test _parse_summary_md — parsing logic
# ---------------------------------------------------------------------------


class TestParseSummaryMd:
    """Tests for the _parse_summary_md helper function."""

    def test_parses_minimal_summary(self, tmp_path: Path) -> None:
        """Minimal SUMMARY.md is parsed correctly."""
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        summary_path = tasks_dir / "SUMMARY.md"
        summary_path.write_text(MINIMAL_SUMMARY, encoding="utf-8")

        data = _parse_summary_md(summary_path)

        assert data is not None
        assert data["date"] == "2026-05-18 14:30"
        assert data["duration"] == "12:34"
        assert data["result"] == "success"
        assert data["goal"] == "Add a new feature to the application"
        assert len(data["tasks"]) == 1
        assert data["tasks"][0]["task"] == "T01"
        assert data["tasks"][0]["title"] == "setup_project"
        assert data["tasks"][0]["status"] == "✓ Done"

    def test_parses_multi_task_summary(self, tmp_path: Path) -> None:
        """Multi-task SUMMARY.md parses all task rows."""
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        summary_path = tasks_dir / "SUMMARY.md"
        summary_path.write_text(MULTI_TASK_SUMMARY, encoding="utf-8")

        data = _parse_summary_md(summary_path)

        assert data is not None
        assert len(data["tasks"]) == 3
        assert data["tasks"][0]["task"] == "T01"
        assert data["tasks"][1]["task"] == "T02"
        assert data["tasks"][2]["task"] == "T03"
        assert data["tasks"][1]["attempts"] == "2"

    def test_parses_failed_result(self, tmp_path: Path) -> None:
        """SUMMARY.md with failed tasks produces result='failed'."""
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        summary_path = tasks_dir / "SUMMARY.md"
        summary_path.write_text(FAILED_TASK_SUMMARY, encoding="utf-8")

        data = _parse_summary_md(summary_path)

        assert data is not None
        assert data["result"] == "failed"
        assert len(data["tasks"]) == 2
        assert data["tasks"][0]["status"] == "✓ Done"
        assert data["tasks"][1]["status"] == "✗ Failed"

    def test_parses_totals_section(self, tmp_path: Path) -> None:
        """Totals section is parsed into key-value pairs."""
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        summary_path = tasks_dir / "SUMMARY.md"
        summary_path.write_text(MINIMAL_SUMMARY, encoding="utf-8")

        data = _parse_summary_md(summary_path)

        assert data is not None
        assert "Tasks" in data["totals"]
        assert data["totals"]["Tasks"] == "1/1 done"
        assert "Duration" in data["totals"]
        assert "Total tokens" in data["totals"]

    def test_parses_insights_section(self, tmp_path: Path) -> None:
        """Insights section is parsed into key-value pairs."""
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        summary_path = tasks_dir / "SUMMARY.md"
        summary_path.write_text(MINIMAL_SUMMARY, encoding="utf-8")

        data = _parse_summary_md(summary_path)

        assert data is not None
        assert "Avg duration per task" in data["insights"]
        assert "Slowest task" in data["insights"]

    def test_parses_retrospective_summary(self, tmp_path: Path) -> None:
        """SUMMARY.md with retrospective rounds still parses tasks."""
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        summary_path = tasks_dir / "SUMMARY.md"
        summary_path.write_text(RETROSPECTIVE_SUMMARY, encoding="utf-8")

        data = _parse_summary_md(summary_path)

        assert data is not None
        assert data["result"] == "success"
        assert len(data["tasks"]) == 1
        assert data["tasks"][0]["task"] == "T01"

    def test_skips_task_header_row(self, tmp_path: Path) -> None:
        """The header row of the tasks table is not included in output."""
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        summary_path = tasks_dir / "SUMMARY.md"
        summary_path.write_text(MINIMAL_SUMMARY, encoding="utf-8")

        data = _parse_summary_md(summary_path)

        assert data is not None
        # Header row has cells[0] == "Task" and must be skipped
        assert all(t["task"] != "Task" for t in data["tasks"])

    def test_empty_summary_returns_empty_fields(self, tmp_path: Path) -> None:
        """An empty SUMMARY.md returns a dict with empty/zeroed fields."""
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        summary_path = tasks_dir / "SUMMARY.md"
        summary_path.write_text("", encoding="utf-8")

        data = _parse_summary_md(summary_path)

        assert data is not None
        assert data["date"] == ""
        assert data["duration"] == ""
        assert data["result"] == "unknown"
        assert data["goal"] == ""
        assert data["tasks"] == []
        assert data["totals"] == {}
        assert data["insights"] == {}

    def test_summary_with_no_goal_section(self, tmp_path: Path) -> None:
        """SUMMARY.md without a Goal section still parses."""
        content = """\
# The Architect — Run Summary

**Date:** 2026-05-18 14:30
**Duration:** 5:00
**Result:** ✓ All tasks completed

## Tasks

| Task | Title | Status | Attempts | Model | Duration | Tokens |
|------|-------|--------|----------|-------|----------|--------|
| T01 | test_task | ✓ Done | 1 | gpt-4o | 3:00 | 5K |

## Totals

- **Tasks:** 1/1 done
- **Duration:** 5:00
- **Total tokens:** 5K
"""
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        summary_path = tasks_dir / "SUMMARY.md"
        summary_path.write_text(content, encoding="utf-8")

        data = _parse_summary_md(summary_path)

        assert data is not None
        assert data["goal"] == ""
        assert len(data["tasks"]) == 1

    def test_summary_with_no_insights_section(self, tmp_path: Path) -> None:
        """SUMMARY.md without Insights section still parses."""
        content = """\
# The Architect — Run Summary

**Date:** 2026-05-18 14:30
**Duration:** 5:00
**Result:** ✓ All tasks completed

## Tasks

| Task | Title | Status | Attempts | Model | Duration | Tokens |
|------|-------|--------|----------|-------|----------|--------|
| T01 | test_task | ✓ Done | 1 | gpt-4o | 3:00 | 5K |

## Totals

- **Tasks:** 1/1 done
- **Duration:** 5:00
- **Total tokens:** 5K
"""
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        summary_path = tasks_dir / "SUMMARY.md"
        summary_path.write_text(content, encoding="utf-8")

        data = _parse_summary_md(summary_path)

        assert data is not None
        assert data["insights"] == {}

    def test_corrupted_summary_still_parses_partial(self, tmp_path: Path) -> None:
        """Corrupted SUMMARY.md still returns partial data."""
        content = """\
# The Architect — Run Summary

**Date:** 2026-05-18 14:30
**Duration:** 5:00
**Result:** ✓ All tasks completed

## Tasks

| Task | Title | Status
|------|-------|--------|
THIS IS CORRUPTED GARBAGE
"""
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        summary_path = tasks_dir / "SUMMARY.md"
        summary_path.write_text(content, encoding="utf-8")

        data = _parse_summary_md(summary_path)

        # Should still parse what it can
        assert data is not None
        assert data["date"] == "2026-05-18 14:30"
        assert data["result"] == "success"

    def test_task_with_missing_fields(self, tmp_path: Path) -> None:
        """Task rows with fewer columns get empty strings for missing fields."""
        content = """\
# The Architect — Run Summary

**Date:** 2026-05-18 14:30
**Duration:** 5:00
**Result:** ✓ All tasks completed

## Tasks

| Task | Title | Status | Attempts | Model | Duration | Tokens |
|------|-------|--------|----------|-------|----------|--------|
| T01 | short_row | ✓ Done |

## Totals

- **Tasks:** 1/1 done
- **Duration:** 5:00
- **Total tokens:** 5K
"""
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        summary_path = tasks_dir / "SUMMARY.md"
        summary_path.write_text(content, encoding="utf-8")

        data = _parse_summary_md(summary_path)

        assert data is not None
        assert len(data["tasks"]) == 1
        assert data["tasks"][0]["task"] == "T01"
        assert data["tasks"][0]["title"] == "short_row"
        assert data["tasks"][0]["status"] == "✓ Done"
        # Missing fields should be empty strings
        assert data["tasks"][0]["attempts"] == ""
        assert data["tasks"][0]["model"] == ""


# ---------------------------------------------------------------------------
# Test _format_report_json — JSON serialization
# ---------------------------------------------------------------------------


class TestFormatReportJson:
    """Tests for the _format_report_json helper function."""

    def test_produces_valid_json(self) -> None:
        """Output is valid JSON that can be parsed."""
        data = {
            "date": "2026-05-18 14:30",
            "duration": "12:34",
            "result": "success",
            "goal": "Test goal",
            "tasks": [{"task": "T01", "title": "test", "status": "✓ Done"}],
            "totals": {"Tasks": "1/1 done"},
            "insights": {},
        }
        output = _format_report_json("/project/path", data)
        parsed = json.loads(output)

        assert parsed["project"] == "/project/path"
        assert parsed["date"] == "2026-05-18 14:30"
        assert parsed["result"] == "success"
        assert len(parsed["tasks"]) == 1

    def test_json_contains_all_required_keys(self) -> None:
        """JSON output has all required top-level keys."""
        data = {
            "date": "2026-05-18",
            "duration": "5:00",
            "result": "success",
            "goal": "",
            "tasks": [],
            "totals": {},
            "insights": {},
        }
        output = _format_report_json("/path", data)
        parsed = json.loads(output)

        required_keys = {
            "project",
            "date",
            "duration",
            "result",
            "goal",
            "tasks",
            "totals",
            "insights",
        }
        assert set(parsed.keys()) == required_keys

    def test_json_handles_empty_data(self) -> None:
        """Empty data dict produces valid JSON with empty values."""
        output = _format_report_json("/path", {})
        parsed = json.loads(output)

        assert parsed["project"] == "/path"
        assert parsed["date"] == ""
        assert parsed["result"] == ""
        assert parsed["tasks"] == []
        assert parsed["totals"] == {}
        assert parsed["insights"] == {}

    def test_json_preserves_task_details(self) -> None:
        """Task details with all fields are preserved in JSON."""
        data = {
            "date": "2026-05-18",
            "duration": "10:00",
            "result": "success",
            "goal": "Goal text",
            "tasks": [
                {
                    "task": "T01",
                    "title": "test_task",
                    "status": "✓ Done",
                    "attempts": "1",
                    "model": "gpt-4o",
                    "duration": "5:00",
                    "tokens": "10K",
                }
            ],
            "totals": {"Tasks": "1/1 done"},
            "insights": {"Avg duration per task": "5:00"},
        }
        output = _format_report_json("/path", data)
        parsed = json.loads(output)

        task = parsed["tasks"][0]
        assert task["task"] == "T01"
        assert task["title"] == "test_task"
        assert task["attempts"] == "1"
        assert task["model"] == "gpt-4o"
        assert task["duration"] == "5:00"
        assert task["tokens"] == "10K"

    def test_json_indented_output(self) -> None:
        """JSON output uses 2-space indentation for readability."""
        output = _format_report_json("/path", {"date": "2026-05-18"})
        # Indented output will have newlines and spaces
        assert "\n" in output
        assert "  " in output


# ---------------------------------------------------------------------------
# CLI integration tests — report_cmd
# ---------------------------------------------------------------------------


class TestReportCliCommand:
    """CLI integration tests for `architect report` command."""

    def _create_summary(self, tmp_path: Path, content: str) -> Path:
        """Helper to create a SUMMARY.md file in tmp_path/tasks/."""
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir(exist_ok=True)
        summary_path = tasks_dir / "SUMMARY.md"
        summary_path.write_text(content, encoding="utf-8")
        return summary_path

    def test_basic_report_shows_rich_table(self, tmp_path: Path) -> None:
        """Basic report command renders Rich table output."""
        self._create_summary(tmp_path, MINIMAL_SUMMARY)

        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path)])

        assert result.exit_code == 0, result.output
        assert "The Architect" in result.output
        assert "Run Report" in result.output
        assert "2026-05-18" in result.output

    def test_report_json_output_is_valid(self, tmp_path: Path) -> None:
        """Report --json produces valid JSON."""
        self._create_summary(tmp_path, MINIMAL_SUMMARY)

        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path), "--json"])

        assert result.exit_code == 0, result.output
        parsed = json.loads(result.output)
        assert parsed["result"] == "success"
        assert parsed["date"] == "2026-05-18 14:30"
        assert len(parsed["tasks"]) == 1

    def test_report_json_has_all_keys(self, tmp_path: Path) -> None:
        """Report --json output contains all required keys."""
        self._create_summary(tmp_path, MINIMAL_SUMMARY)

        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path), "--json"])

        assert result.exit_code == 0, result.output
        parsed = json.loads(result.output)
        required_keys = {
            "project",
            "date",
            "duration",
            "result",
            "goal",
            "tasks",
            "totals",
            "insights",
        }
        assert set(parsed.keys()) == required_keys

    def test_report_json_with_multi_task(self, tmp_path: Path) -> None:
        """Report --json with multiple tasks preserves all task data."""
        self._create_summary(tmp_path, MULTI_TASK_SUMMARY)

        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path), "--json"])

        assert result.exit_code == 0, result.output
        parsed = json.loads(result.output)
        assert len(parsed["tasks"]) == 3
        assert parsed["tasks"][0]["task"] == "T01"
        assert parsed["tasks"][1]["task"] == "T02"
        assert parsed["tasks"][2]["task"] == "T03"
        assert parsed["tasks"][1]["attempts"] == "2"

    def test_report_json_with_failed_tasks(self, tmp_path: Path) -> None:
        """Report --json correctly reports failed result."""
        self._create_summary(tmp_path, FAILED_TASK_SUMMARY)

        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path), "--json"])

        assert result.exit_code == 0, result.output
        parsed = json.loads(result.output)
        assert parsed["result"] == "failed"
        assert len(parsed["tasks"]) == 2

    def test_report_json_project_path_set(self, tmp_path: Path) -> None:
        """Report --json includes the project path."""
        self._create_summary(tmp_path, MINIMAL_SUMMARY)

        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path), "--json"])

        assert result.exit_code == 0, result.output
        parsed = json.loads(result.output)
        assert parsed["project"] == str(tmp_path)

    def test_report_with_short_project_flag(self, tmp_path: Path) -> None:
        """Report -p (short flag) works identically to --project."""
        self._create_summary(tmp_path, MINIMAL_SUMMARY)

        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path)])

        assert result.exit_code == 0, result.output
        assert "Run Report" in result.output

    def test_report_shows_goal_section(self, tmp_path: Path) -> None:
        """Report table output includes the goal when present."""
        self._create_summary(tmp_path, MINIMAL_SUMMARY)

        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path)])

        assert result.exit_code == 0, result.output
        assert "Goal" in result.output
        assert "Add a new feature" in result.output

    def test_report_shows_totals_section(self, tmp_path: Path) -> None:
        """Report table output includes totals when present."""
        self._create_summary(tmp_path, MINIMAL_SUMMARY)

        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path)])

        assert result.exit_code == 0, result.output
        assert "Totals" in result.output

    def test_report_shows_insights_section(self, tmp_path: Path) -> None:
        """Report table output includes insights when present."""
        self._create_summary(tmp_path, MINIMAL_SUMMARY)

        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path)])

        assert result.exit_code == 0, result.output
        assert "Insights" in result.output

    def test_report_json_with_retrospective(self, tmp_path: Path) -> None:
        """Report --json with retrospective summary still parses tasks."""
        self._create_summary(tmp_path, RETROSPECTIVE_SUMMARY)

        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path), "--json"])

        assert result.exit_code == 0, result.output
        parsed = json.loads(result.output)
        assert parsed["result"] == "success"
        assert len(parsed["tasks"]) == 1
        assert parsed["tasks"][0]["task"] == "T01"

    def test_report_table_shows_success_result(self, tmp_path: Path) -> None:
        """Report table displays success result with checkmark."""
        self._create_summary(tmp_path, MINIMAL_SUMMARY)

        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path)])

        assert result.exit_code == 0, result.output
        assert "success" in result.output.lower()

    def test_report_table_shows_failed_result(self, tmp_path: Path) -> None:
        """Report table displays failed result."""
        self._create_summary(tmp_path, FAILED_TASK_SUMMARY)

        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path)])

        assert result.exit_code == 0, result.output
        assert "failed" in result.output.lower()


# ---------------------------------------------------------------------------
# Edge case tests
# ---------------------------------------------------------------------------


class TestReportEdgeCases:
    """Tests for edge cases: missing files, empty files, corrupted files."""

    def test_no_summary_md_exits_1(self, tmp_path: Path) -> None:
        """Report exits with code 1 when SUMMARY.md does not exist."""
        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path)])

        assert result.exit_code == 1
        assert "No run summary found" in result.output

    def test_no_summary_md_json_exits_1(self, tmp_path: Path) -> None:
        """Report --json exits with code 1 when SUMMARY.md does not exist."""
        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path), "--json"])

        assert result.exit_code == 1
        assert "No run summary found" in result.output

    def test_empty_summary_md_still_works(self, tmp_path: Path) -> None:
        """Report with empty SUMMARY.md renders without crashing."""
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        (tasks_dir / "SUMMARY.md").write_text("", encoding="utf-8")

        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path)])

        assert result.exit_code == 0, result.output
        assert "Run Report" in result.output

    def test_empty_summary_md_json_works(self, tmp_path: Path) -> None:
        """Report --json with empty SUMMARY.md produces valid JSON."""
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        (tasks_dir / "SUMMARY.md").write_text("", encoding="utf-8")

        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path), "--json"])

        assert result.exit_code == 0, result.output
        parsed = json.loads(result.output)
        assert parsed["result"] == "unknown"
        assert parsed["tasks"] == []
        assert parsed["totals"] == {}
        assert parsed["insights"] == {}

    def test_tasks_dir_missing_exits_1(self, tmp_path: Path) -> None:
        """Report exits 1 when tasks/ directory does not exist."""
        # tmp_path has no tasks/ directory at all
        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path)])

        assert result.exit_code == 1
        assert "No run summary found" in result.output

    def test_summary_with_no_tasks_section(self, tmp_path: Path) -> None:
        """SUMMARY.md without Tasks section parses gracefully."""
        content = """\
# The Architect — Run Summary

**Date:** 2026-05-18 14:30
**Duration:** 5:00
**Result:** ✓ All tasks completed
"""
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        (tasks_dir / "SUMMARY.md").write_text(content, encoding="utf-8")

        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path), "--json"])

        assert result.exit_code == 0, result.output
        parsed = json.loads(result.output)
        assert parsed["tasks"] == []

    def test_summary_with_random_garbage(self, tmp_path: Path) -> None:
        """SUMMARY.md with random garbage still parses what it can."""
        content = """\
# The Architect — Run Summary

**Date:** 2026-05-18 14:30
**Duration:** 5:00
**Result:** ✓ All tasks completed

THIS IS RANDOM GARBAGE THAT IS NOT A TABLE
!!!@@@###$$$%%%^^^&&&***
"""
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        (tasks_dir / "SUMMARY.md").write_text(content, encoding="utf-8")

        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path), "--json"])

        assert result.exit_code == 0, result.output
        parsed = json.loads(result.output)
        assert parsed["result"] == "success"
        assert parsed["date"] == "2026-05-18 14:30"

    def test_summary_with_unicode_content(self, tmp_path: Path) -> None:
        """SUMMARY.md with unicode characters parses correctly."""
        content = """\
# The Architect — Run Summary

**Date:** 2026-05-18 14:30
**Duration:** 5:00
**Result:** ✓ All tasks completed

## Goal

Add émojis 🚀 and ünicödé support

## Tasks

| Task | Title | Status | Attempts | Model | Duration | Tokens |
|------|-------|--------|----------|-------|----------|--------|
| T01 | test_üñîcödé | ✓ Done | 1 | gpt-4o | 3:00 | 5K |

## Totals

- **Tasks:** 1/1 done
- **Duration:** 5:00
- **Total tokens:** 5K
"""
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        (tasks_dir / "SUMMARY.md").write_text(content, encoding="utf-8")

        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path), "--json"])

        assert result.exit_code == 0, result.output
        parsed = json.loads(result.output)
        assert len(parsed["tasks"]) == 1
        assert parsed["tasks"][0]["task"] == "T01"

    def test_summary_without_totals_section(self, tmp_path: Path) -> None:
        """SUMMARY.md without Totals section parses gracefully."""
        content = """\
# The Architect — Run Summary

**Date:** 2026-05-18 14:30
**Duration:** 5:00
**Result:** ✓ All tasks completed

## Tasks

| Task | Title | Status | Attempts | Model | Duration | Tokens |
|------|-------|--------|----------|-------|----------|--------|
| T01 | minimal | ✓ Done | 1 | gpt-4o | 3:00 | 5K |
"""
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        (tasks_dir / "SUMMARY.md").write_text(content, encoding="utf-8")

        result = CliRunner().invoke(main, ["report", "-p", str(tmp_path), "--json"])

        assert result.exit_code == 0, result.output
        parsed = json.loads(result.output)
        assert parsed["totals"] == {}
        assert len(parsed["tasks"]) == 1

    def test_summary_with_multiple_duration_lines(self, tmp_path: Path) -> None:
        """When multiple Duration lines exist, the first is used."""
        content = """\
# The Architect — Run Summary

**Date:** 2026-05-18 14:30
**Duration:** 10:00
**Result:** ✓ All tasks completed

## Tasks

| Task | Title | Status | Attempts | Model | Duration | Tokens |
|------|-------|--------|----------|-------|----------|--------|
| T01 | task1 | ✓ Done | 1 | gpt-4o | 5:00 | 5K |

## Totals

- **Tasks:** 1/1 done
- **Duration:** 10:00
- **Total tokens:** 5K
"""
        tasks_dir = tmp_path / "tasks"
        tasks_dir.mkdir()
        (tasks_dir / "SUMMARY.md").write_text(content, encoding="utf-8")

        data = _parse_summary_md(tasks_dir / "SUMMARY.md")

        assert data is not None
        # First Duration line should be used
        assert data["duration"] == "10:00"
